# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/mingj/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/183.4886.39/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/mingj/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/183.4886.39/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mingj/Documents/ccn/ip-ndn-stack_cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mingj/Documents/ccn/ip-ndn-stack_cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/mingj/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/183.4886.39/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/mingj/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/183.4886.39/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mingj/Documents/ccn/ip-ndn-stack_cpp/CMakeFiles /home/mingj/Documents/ccn/ip-ndn-stack_cpp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mingj/Documents/ccn/ip-ndn-stack_cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ip_ndn_stack_cpp

# Build rule for target.
ip_ndn_stack_cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ip_ndn_stack_cpp
.PHONY : ip_ndn_stack_cpp

# fast build rule for target.
ip_ndn_stack_cpp/fast:
	$(MAKE) -f CMakeFiles/ip_ndn_stack_cpp.dir/build.make CMakeFiles/ip_ndn_stack_cpp.dir/build
.PHONY : ip_ndn_stack_cpp/fast

helper/JSONCPPHelper.o: helper/JSONCPPHelper.cpp.o

.PHONY : helper/JSONCPPHelper.o

# target to build an object file
helper/JSONCPPHelper.cpp.o:
	$(MAKE) -f CMakeFiles/ip_ndn_stack_cpp.dir/build.make CMakeFiles/ip_ndn_stack_cpp.dir/helper/JSONCPPHelper.cpp.o
.PHONY : helper/JSONCPPHelper.cpp.o

helper/JSONCPPHelper.i: helper/JSONCPPHelper.cpp.i

.PHONY : helper/JSONCPPHelper.i

# target to preprocess a source file
helper/JSONCPPHelper.cpp.i:
	$(MAKE) -f CMakeFiles/ip_ndn_stack_cpp.dir/build.make CMakeFiles/ip_ndn_stack_cpp.dir/helper/JSONCPPHelper.cpp.i
.PHONY : helper/JSONCPPHelper.cpp.i

helper/JSONCPPHelper.s: helper/JSONCPPHelper.cpp.s

.PHONY : helper/JSONCPPHelper.s

# target to generate assembly for a file
helper/JSONCPPHelper.cpp.s:
	$(MAKE) -f CMakeFiles/ip_ndn_stack_cpp.dir/build.make CMakeFiles/ip_ndn_stack_cpp.dir/helper/JSONCPPHelper.cpp.s
.PHONY : helper/JSONCPPHelper.cpp.s

helper/LibPcapHelper.o: helper/LibPcapHelper.cpp.o

.PHONY : helper/LibPcapHelper.o

# target to build an object file
helper/LibPcapHelper.cpp.o:
	$(MAKE) -f CMakeFiles/ip_ndn_stack_cpp.dir/build.make CMakeFiles/ip_ndn_stack_cpp.dir/helper/LibPcapHelper.cpp.o
.PHONY : helper/LibPcapHelper.cpp.o

helper/LibPcapHelper.i: helper/LibPcapHelper.cpp.i

.PHONY : helper/LibPcapHelper.i

# target to preprocess a source file
helper/LibPcapHelper.cpp.i:
	$(MAKE) -f CMakeFiles/ip_ndn_stack_cpp.dir/build.make CMakeFiles/ip_ndn_stack_cpp.dir/helper/LibPcapHelper.cpp.i
.PHONY : helper/LibPcapHelper.cpp.i

helper/LibPcapHelper.s: helper/LibPcapHelper.cpp.s

.PHONY : helper/LibPcapHelper.s

# target to generate assembly for a file
helper/LibPcapHelper.cpp.s:
	$(MAKE) -f CMakeFiles/ip_ndn_stack_cpp.dir/build.make CMakeFiles/ip_ndn_stack_cpp.dir/helper/LibPcapHelper.cpp.s
.PHONY : helper/LibPcapHelper.cpp.s

helper/MapCacheHelper.o: helper/MapCacheHelper.cpp.o

.PHONY : helper/MapCacheHelper.o

# target to build an object file
helper/MapCacheHelper.cpp.o:
	$(MAKE) -f CMakeFiles/ip_ndn_stack_cpp.dir/build.make CMakeFiles/ip_ndn_stack_cpp.dir/helper/MapCacheHelper.cpp.o
.PHONY : helper/MapCacheHelper.cpp.o

helper/MapCacheHelper.i: helper/MapCacheHelper.cpp.i

.PHONY : helper/MapCacheHelper.i

# target to preprocess a source file
helper/MapCacheHelper.cpp.i:
	$(MAKE) -f CMakeFiles/ip_ndn_stack_cpp.dir/build.make CMakeFiles/ip_ndn_stack_cpp.dir/helper/MapCacheHelper.cpp.i
.PHONY : helper/MapCacheHelper.cpp.i

helper/MapCacheHelper.s: helper/MapCacheHelper.cpp.s

.PHONY : helper/MapCacheHelper.s

# target to generate assembly for a file
helper/MapCacheHelper.cpp.s:
	$(MAKE) -f CMakeFiles/ip_ndn_stack_cpp.dir/build.make CMakeFiles/ip_ndn_stack_cpp.dir/helper/MapCacheHelper.cpp.s
.PHONY : helper/MapCacheHelper.cpp.s

helper/NDNHelper.o: helper/NDNHelper.cpp.o

.PHONY : helper/NDNHelper.o

# target to build an object file
helper/NDNHelper.cpp.o:
	$(MAKE) -f CMakeFiles/ip_ndn_stack_cpp.dir/build.make CMakeFiles/ip_ndn_stack_cpp.dir/helper/NDNHelper.cpp.o
.PHONY : helper/NDNHelper.cpp.o

helper/NDNHelper.i: helper/NDNHelper.cpp.i

.PHONY : helper/NDNHelper.i

# target to preprocess a source file
helper/NDNHelper.cpp.i:
	$(MAKE) -f CMakeFiles/ip_ndn_stack_cpp.dir/build.make CMakeFiles/ip_ndn_stack_cpp.dir/helper/NDNHelper.cpp.i
.PHONY : helper/NDNHelper.cpp.i

helper/NDNHelper.s: helper/NDNHelper.cpp.s

.PHONY : helper/NDNHelper.s

# target to generate assembly for a file
helper/NDNHelper.cpp.s:
	$(MAKE) -f CMakeFiles/ip_ndn_stack_cpp.dir/build.make CMakeFiles/ip_ndn_stack_cpp.dir/helper/NDNHelper.cpp.s
.PHONY : helper/NDNHelper.cpp.s

helper/PcapHelper.o: helper/PcapHelper.cpp.o

.PHONY : helper/PcapHelper.o

# target to build an object file
helper/PcapHelper.cpp.o:
	$(MAKE) -f CMakeFiles/ip_ndn_stack_cpp.dir/build.make CMakeFiles/ip_ndn_stack_cpp.dir/helper/PcapHelper.cpp.o
.PHONY : helper/PcapHelper.cpp.o

helper/PcapHelper.i: helper/PcapHelper.cpp.i

.PHONY : helper/PcapHelper.i

# target to preprocess a source file
helper/PcapHelper.cpp.i:
	$(MAKE) -f CMakeFiles/ip_ndn_stack_cpp.dir/build.make CMakeFiles/ip_ndn_stack_cpp.dir/helper/PcapHelper.cpp.i
.PHONY : helper/PcapHelper.cpp.i

helper/PcapHelper.s: helper/PcapHelper.cpp.s

.PHONY : helper/PcapHelper.s

# target to generate assembly for a file
helper/PcapHelper.cpp.s:
	$(MAKE) -f CMakeFiles/ip_ndn_stack_cpp.dir/build.make CMakeFiles/ip_ndn_stack_cpp.dir/helper/PcapHelper.cpp.s
.PHONY : helper/PcapHelper.cpp.s

helper/RawSocketHelper.o: helper/RawSocketHelper.cpp.o

.PHONY : helper/RawSocketHelper.o

# target to build an object file
helper/RawSocketHelper.cpp.o:
	$(MAKE) -f CMakeFiles/ip_ndn_stack_cpp.dir/build.make CMakeFiles/ip_ndn_stack_cpp.dir/helper/RawSocketHelper.cpp.o
.PHONY : helper/RawSocketHelper.cpp.o

helper/RawSocketHelper.i: helper/RawSocketHelper.cpp.i

.PHONY : helper/RawSocketHelper.i

# target to preprocess a source file
helper/RawSocketHelper.cpp.i:
	$(MAKE) -f CMakeFiles/ip_ndn_stack_cpp.dir/build.make CMakeFiles/ip_ndn_stack_cpp.dir/helper/RawSocketHelper.cpp.i
.PHONY : helper/RawSocketHelper.cpp.i

helper/RawSocketHelper.s: helper/RawSocketHelper.cpp.s

.PHONY : helper/RawSocketHelper.s

# target to generate assembly for a file
helper/RawSocketHelper.cpp.s:
	$(MAKE) -f CMakeFiles/ip_ndn_stack_cpp.dir/build.make CMakeFiles/ip_ndn_stack_cpp.dir/helper/RawSocketHelper.cpp.s
.PHONY : helper/RawSocketHelper.cpp.s

helper/SetHelper.o: helper/SetHelper.cpp.o

.PHONY : helper/SetHelper.o

# target to build an object file
helper/SetHelper.cpp.o:
	$(MAKE) -f CMakeFiles/ip_ndn_stack_cpp.dir/build.make CMakeFiles/ip_ndn_stack_cpp.dir/helper/SetHelper.cpp.o
.PHONY : helper/SetHelper.cpp.o

helper/SetHelper.i: helper/SetHelper.cpp.i

.PHONY : helper/SetHelper.i

# target to preprocess a source file
helper/SetHelper.cpp.i:
	$(MAKE) -f CMakeFiles/ip_ndn_stack_cpp.dir/build.make CMakeFiles/ip_ndn_stack_cpp.dir/helper/SetHelper.cpp.i
.PHONY : helper/SetHelper.cpp.i

helper/SetHelper.s: helper/SetHelper.cpp.s

.PHONY : helper/SetHelper.s

# target to generate assembly for a file
helper/SetHelper.cpp.s:
	$(MAKE) -f CMakeFiles/ip_ndn_stack_cpp.dir/build.make CMakeFiles/ip_ndn_stack_cpp.dir/helper/SetHelper.cpp.s
.PHONY : helper/SetHelper.cpp.s

libpcapcapture/packet.o: libpcapcapture/packet.cpp.o

.PHONY : libpcapcapture/packet.o

# target to build an object file
libpcapcapture/packet.cpp.o:
	$(MAKE) -f CMakeFiles/ip_ndn_stack_cpp.dir/build.make CMakeFiles/ip_ndn_stack_cpp.dir/libpcapcapture/packet.cpp.o
.PHONY : libpcapcapture/packet.cpp.o

libpcapcapture/packet.i: libpcapcapture/packet.cpp.i

.PHONY : libpcapcapture/packet.i

# target to preprocess a source file
libpcapcapture/packet.cpp.i:
	$(MAKE) -f CMakeFiles/ip_ndn_stack_cpp.dir/build.make CMakeFiles/ip_ndn_stack_cpp.dir/libpcapcapture/packet.cpp.i
.PHONY : libpcapcapture/packet.cpp.i

libpcapcapture/packet.s: libpcapcapture/packet.cpp.s

.PHONY : libpcapcapture/packet.s

# target to generate assembly for a file
libpcapcapture/packet.cpp.s:
	$(MAKE) -f CMakeFiles/ip_ndn_stack_cpp.dir/build.make CMakeFiles/ip_ndn_stack_cpp.dir/libpcapcapture/packet.cpp.s
.PHONY : libpcapcapture/packet.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/ip_ndn_stack_cpp.dir/build.make CMakeFiles/ip_ndn_stack_cpp.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/ip_ndn_stack_cpp.dir/build.make CMakeFiles/ip_ndn_stack_cpp.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/ip_ndn_stack_cpp.dir/build.make CMakeFiles/ip_ndn_stack_cpp.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... ip_ndn_stack_cpp"
	@echo "... edit_cache"
	@echo "... helper/JSONCPPHelper.o"
	@echo "... helper/JSONCPPHelper.i"
	@echo "... helper/JSONCPPHelper.s"
	@echo "... helper/LibPcapHelper.o"
	@echo "... helper/LibPcapHelper.i"
	@echo "... helper/LibPcapHelper.s"
	@echo "... helper/MapCacheHelper.o"
	@echo "... helper/MapCacheHelper.i"
	@echo "... helper/MapCacheHelper.s"
	@echo "... helper/NDNHelper.o"
	@echo "... helper/NDNHelper.i"
	@echo "... helper/NDNHelper.s"
	@echo "... helper/PcapHelper.o"
	@echo "... helper/PcapHelper.i"
	@echo "... helper/PcapHelper.s"
	@echo "... helper/RawSocketHelper.o"
	@echo "... helper/RawSocketHelper.i"
	@echo "... helper/RawSocketHelper.s"
	@echo "... helper/SetHelper.o"
	@echo "... helper/SetHelper.i"
	@echo "... helper/SetHelper.s"
	@echo "... libpcapcapture/packet.o"
	@echo "... libpcapcapture/packet.i"
	@echo "... libpcapcapture/packet.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

