#!/usr/bin/expect
set timeout 2
set password node9
spawn ssh node9@125.218.56.11

expect {
    "(yes/no)?" {
        send "yes\r";
        expect "password:";
        send "${password}\r";
        exp_continue;
    }
    "password:" {
        send "${password}\r";
        exp_continue;
    }
}
interact
