#!/usr/bin/expect
set timeout 2
set password node7
spawn ssh node7@ns.qjm253.cn -p 9607

expect {
    "(yes/no)?" {
        send "yes\r";
        expect "password:";
        send "${password}\r";
        exp_continue;
    }
    "password:" {
        send "${password}\r";
        exp_continue;
    }
}
interact
