#!/usr/bin/expect
set timeout 2
set password node10
spawn ssh node10@125.218.56.2

expect {
    "(yes/no)?" {
        send "yes\r";
        expect "password:";
        send "${password}\r";
        exp_continue;
    }
    "password:" {
        send "${password}\r";
        exp_continue;
    }
}
interact
