#!/usr/bin/expect
set timeout 2
set password node3
spawn ssh node3@ft.qjm253.cn -p 9603

expect {
    "(yes/no)?" {
        send "yes\r";
        expect "password:";
        send "${password}\r";
        exp_continue;
    }
    "password:" {
        send "${password}\r";
        exp_continue;
    }
}
interact
