#!/usr/bin/expect
set timeout 2
set password node14
spawn ssh node14@125.218.56.14

expect {
    "(yes/no)?" {
        send "yes\r";
        expect "password:";
        send "${password}\r";
        exp_continue;
    }
    "password:" {
        send "${password}\r";
        exp_continue;
    }
}
interact
