#!/usr/bin/expect
set timeout 2
set password node8
spawn ssh node8@ns.qjm253.cn -p 9608

expect {
    "(yes/no)?" {
        send "yes\r";
        expect "password:";
        send "${password}\r";
        exp_continue;
    }
    "password:" {
        send "${password}\r";
        exp_continue;
    }
}
interact
