#!/usr/bin/expect
set timeout 2
set password password
spawn ssh pkusz3@ns.qjm253.cn -p 9609

expect {
    "(yes/no)?" {
        send "yes\r";
        expect "password:";
        send "${password}\r";
        exp_continue;
    }
    "password:" {
        send "${password}\r";
        exp_continue;
    }
}
interact
