#!/usr/bin/expect
set timeout 2
set password pkusz2
spawn ssh pkusz2@lab.pkusz.qjm253.cn -p 9605

expect {
    "(yes/no)?" {
        send "yes\r";
        expect "password:";
        send "${password}\r";
        exp_continue;
    }
    "password:" {
        send "${password}\r";
        exp_continue;
    }
}
interact
